services:
  fitcrack_server:
    image: hranicky/fitcrack_server:2.4.0
    hostname: fitcrack
    command: ./entrypoint-fitcrack.sh
    restart: always

    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      # - "${BOINC_PORT}:${BOINC_PORT}"

    environment:
      USER: root

      # MySQL database environment variables
      DB_HOST: "${FITCRACK_DB_HOST}"
      DB_NAME: "${FITCRACK_DB_NAME}"
      DB_USER: "${FITCRACK_DB_USER}"
      DB_PW: "${FITCRACK_DB_PW}"

      # Fitcrack WebAdmin environment variables
      WEBADMIN_HOST: "${WEBADMIN_HOST}"
      WEBADMIN_PROTO: "${WEBADMIN_PROTO}"
      BACKEND_PORT: "${BACKEND_PORT}"
      FRONTEND_PORT: "${FRONTEND_PORT}"
      SSL_WEBADMIN: "${SSL_WEBADMIN}"
      WEBADMIN_USER: "${WEBADMIN_LOGIN}"
      WEBADMIN_EMAIL: "${WEBADMIN_EMAIL}"
      WEBADMIN_PW: "${WEBADMIN_PW}"

      DYNAMIC_BACKEND_URL: "${DYNAMIC_BACKEND_URL}"

      # BOINC server environment variables
      BOINC_HOST: "${BOINC_HOST}"
      BOINC_PROTO: "${BOINC_PROTO}"
      BOINC_PORT: "${BOINC_PORT}"
      SSL_BOINC: "${SSL_BOINC}"
      BOINC_URL: "${BOINC_PROTO}://${BOINC_HOST}:${BOINC_PORT}"
      BOINC_USER: boincadm
      BOINC_GROUP: boincadm
      BOINC_HOME: /home/boincadm
      BOINC_PROJECT: fitcrack
      BOINC_PROJECT_DIR: /home/boincadm/projects/fitcrack
      OPS_LOGIN: "${WEBADMIN_LOGIN}"
      OPS_PW: "${WEBADMIN_PW}"
      SERVICE_INSTALL: "y"
      PROJECT_HTTPD_CONF: /home/boincadm/projects/fitcrack/fitcrack.httpd.conf

      # SSL certificate file names
      SSL_CERTIFICATE_FILE: "${SSL_CERTIFICATE_FILE}"
      SSL_CERTIFICATE_KEYFILE: "${SSL_CERTIFICATE_KEYFILE}"

      # Apache web server environment variables
      APACHE_USER: www-data
      APACHE_CONFIG_DIR: /etc/apache2
      APACHE_CONFIG_FILE: /etc/apache2/apache2.conf
      APACHE_DOCUMENT_ROOT: /var/www/html
      APACHE_SERVICE: apache2
      PYTHONUNBUFFERED: "1"

    volumes:
      - etc:/etc
      - usr:/usr
      - run:/run
      - boincadm:/home/boincadm
      - mysql:/var/lib/mysql
      - webadmin-be:/var/www/html/fitcrackAPI
      - webadmin-fe:/var/www/html/fitcrackFE
      - ./fitcrack-data/logs:/var/log/fitcrack
      - ./fitcrack-data/certificates:/srv/certificates

volumes:
  etc:
  usr:
  run:
  boincadm:
  mysql:
  webadmin-be:
  webadmin-fe:
  logs:
  certificates:
