// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_91f3f3f7c00eaf96, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type NextRequest struct {
	Terminals            uint64   `protobuf:"varint,1,opt,name=terminals,proto3" json:"terminals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NextRequest) Reset()         { *m = NextRequest{} }
func (m *NextRequest) String() string { return proto.CompactTextString(m) }
func (*NextRequest) ProtoMessage()    {}
func (*NextRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_91f3f3f7c00eaf96, []int{1}
}
func (m *NextRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NextRequest.Unmarshal(m, b)
}
func (m *NextRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NextRequest.Marshal(b, m, deterministic)
}
func (dst *NextRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextRequest.Merge(dst, src)
}
func (m *NextRequest) XXX_Size() int {
	return xxx_messageInfo_NextRequest.Size(m)
}
func (m *NextRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NextRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NextRequest proto.InternalMessageInfo

func (m *NextRequest) GetTerminals() uint64 {
	if m != nil {
		return m.Terminals
	}
	return 0
}

type ConnectResponse struct {
	Grammar              *Grammar `protobuf:"bytes,1,opt,name=grammar,proto3" json:"grammar,omitempty"`
	HashList             []string `protobuf:"bytes,2,rep,name=hashList,proto3" json:"hashList,omitempty"`
	HashcatMode          string   `protobuf:"bytes,3,opt,name=hashcatMode,proto3" json:"hashcatMode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectResponse) Reset()         { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()    {}
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_91f3f3f7c00eaf96, []int{2}
}
func (m *ConnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectResponse.Unmarshal(m, b)
}
func (m *ConnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectResponse.Marshal(b, m, deterministic)
}
func (dst *ConnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectResponse.Merge(dst, src)
}
func (m *ConnectResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectResponse.Size(m)
}
func (m *ConnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectResponse proto.InternalMessageInfo

func (m *ConnectResponse) GetGrammar() *Grammar {
	if m != nil {
		return m.Grammar
	}
	return nil
}

func (m *ConnectResponse) GetHashList() []string {
	if m != nil {
		return m.HashList
	}
	return nil
}

func (m *ConnectResponse) GetHashcatMode() string {
	if m != nil {
		return m.HashcatMode
	}
	return ""
}

type ResultResponse struct {
	End                  bool     `protobuf:"varint,1,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResultResponse) Reset()         { *m = ResultResponse{} }
func (m *ResultResponse) String() string { return proto.CompactTextString(m) }
func (*ResultResponse) ProtoMessage()    {}
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_91f3f3f7c00eaf96, []int{3}
}
func (m *ResultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultResponse.Unmarshal(m, b)
}
func (m *ResultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultResponse.Marshal(b, m, deterministic)
}
func (dst *ResultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultResponse.Merge(dst, src)
}
func (m *ResultResponse) XXX_Size() int {
	return xxx_messageInfo_ResultResponse.Size(m)
}
func (m *ResultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResultResponse proto.InternalMessageInfo

func (m *ResultResponse) GetEnd() bool {
	if m != nil {
		return m.End
	}
	return false
}

type CrackingResponse struct {
	Hashes               map[string]string `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CrackingResponse) Reset()         { *m = CrackingResponse{} }
func (m *CrackingResponse) String() string { return proto.CompactTextString(m) }
func (*CrackingResponse) ProtoMessage()    {}
func (*CrackingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_91f3f3f7c00eaf96, []int{4}
}
func (m *CrackingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CrackingResponse.Unmarshal(m, b)
}
func (m *CrackingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CrackingResponse.Marshal(b, m, deterministic)
}
func (dst *CrackingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CrackingResponse.Merge(dst, src)
}
func (m *CrackingResponse) XXX_Size() int {
	return xxx_messageInfo_CrackingResponse.Size(m)
}
func (m *CrackingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CrackingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CrackingResponse proto.InternalMessageInfo

func (m *CrackingResponse) GetHashes() map[string]string {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type Grammar struct {
	RulesFolder          string             `protobuf:"bytes,1,opt,name=rulesFolder,proto3" json:"rulesFolder,omitempty"`
	Sections             []*Section         `protobuf:"bytes,2,rep,name=sections,proto3" json:"sections,omitempty"`
	Mapping              map[string]*IntMap `protobuf:"bytes,3,rep,name=mapping,proto3" json:"mapping,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Grammar) Reset()         { *m = Grammar{} }
func (m *Grammar) String() string { return proto.CompactTextString(m) }
func (*Grammar) ProtoMessage()    {}
func (*Grammar) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_91f3f3f7c00eaf96, []int{5}
}
func (m *Grammar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Grammar.Unmarshal(m, b)
}
func (m *Grammar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Grammar.Marshal(b, m, deterministic)
}
func (dst *Grammar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Grammar.Merge(dst, src)
}
func (m *Grammar) XXX_Size() int {
	return xxx_messageInfo_Grammar.Size(m)
}
func (m *Grammar) XXX_DiscardUnknown() {
	xxx_messageInfo_Grammar.DiscardUnknown(m)
}

var xxx_messageInfo_Grammar proto.InternalMessageInfo

func (m *Grammar) GetRulesFolder() string {
	if m != nil {
		return m.RulesFolder
	}
	return ""
}

func (m *Grammar) GetSections() []*Section {
	if m != nil {
		return m.Sections
	}
	return nil
}

func (m *Grammar) GetMapping() map[string]*IntMap {
	if m != nil {
		return m.Mapping
	}
	return nil
}

type IntMap struct {
	Value                map[string]int32 `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IntMap) Reset()         { *m = IntMap{} }
func (m *IntMap) String() string { return proto.CompactTextString(m) }
func (*IntMap) ProtoMessage()    {}
func (*IntMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_91f3f3f7c00eaf96, []int{6}
}
func (m *IntMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntMap.Unmarshal(m, b)
}
func (m *IntMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntMap.Marshal(b, m, deterministic)
}
func (dst *IntMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntMap.Merge(dst, src)
}
func (m *IntMap) XXX_Size() int {
	return xxx_messageInfo_IntMap.Size(m)
}
func (m *IntMap) XXX_DiscardUnknown() {
	xxx_messageInfo_IntMap.DiscardUnknown(m)
}

var xxx_messageInfo_IntMap proto.InternalMessageInfo

func (m *IntMap) GetValue() map[string]int32 {
	if m != nil {
		return m.Value
	}
	return nil
}

type Replacement struct {
	Probability          float64  `protobuf:"fixed64,1,opt,name=probability,proto3" json:"probability,omitempty"`
	IsTerminal           bool     `protobuf:"varint,2,opt,name=isTerminal,proto3" json:"isTerminal,omitempty"`
	Values               []string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	Function             string   `protobuf:"bytes,4,opt,name=function,proto3" json:"function,omitempty"`
	Pos                  []int32  `protobuf:"varint,5,rep,packed,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Replacement) Reset()         { *m = Replacement{} }
func (m *Replacement) String() string { return proto.CompactTextString(m) }
func (*Replacement) ProtoMessage()    {}
func (*Replacement) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_91f3f3f7c00eaf96, []int{7}
}
func (m *Replacement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Replacement.Unmarshal(m, b)
}
func (m *Replacement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Replacement.Marshal(b, m, deterministic)
}
func (dst *Replacement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Replacement.Merge(dst, src)
}
func (m *Replacement) XXX_Size() int {
	return xxx_messageInfo_Replacement.Size(m)
}
func (m *Replacement) XXX_DiscardUnknown() {
	xxx_messageInfo_Replacement.DiscardUnknown(m)
}

var xxx_messageInfo_Replacement proto.InternalMessageInfo

func (m *Replacement) GetProbability() float64 {
	if m != nil {
		return m.Probability
	}
	return 0
}

func (m *Replacement) GetIsTerminal() bool {
	if m != nil {
		return m.IsTerminal
	}
	return false
}

func (m *Replacement) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *Replacement) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *Replacement) GetPos() []int32 {
	if m != nil {
		return m.Pos
	}
	return nil
}

type Section struct {
	Type                 string         `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name                 string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Replacements         []*Replacement `protobuf:"bytes,3,rep,name=replacements,proto3" json:"replacements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Section) Reset()         { *m = Section{} }
func (m *Section) String() string { return proto.CompactTextString(m) }
func (*Section) ProtoMessage()    {}
func (*Section) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_91f3f3f7c00eaf96, []int{8}
}
func (m *Section) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Section.Unmarshal(m, b)
}
func (m *Section) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Section.Marshal(b, m, deterministic)
}
func (dst *Section) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Section.Merge(dst, src)
}
func (m *Section) XXX_Size() int {
	return xxx_messageInfo_Section.Size(m)
}
func (m *Section) XXX_DiscardUnknown() {
	xxx_messageInfo_Section.DiscardUnknown(m)
}

var xxx_messageInfo_Section proto.InternalMessageInfo

func (m *Section) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Section) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Section) GetReplacements() []*Replacement {
	if m != nil {
		return m.Replacements
	}
	return nil
}

type Items struct {
	PreTerminals         []*TreeItem `protobuf:"bytes,1,rep,name=preTerminals,proto3" json:"preTerminals,omitempty"`
	Terminals            []string    `protobuf:"bytes,2,rep,name=terminals,proto3" json:"terminals,omitempty"`
	TerminalsCount       uint64      `protobuf:"varint,3,opt,name=terminalsCount,proto3" json:"terminalsCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Items) Reset()         { *m = Items{} }
func (m *Items) String() string { return proto.CompactTextString(m) }
func (*Items) ProtoMessage()    {}
func (*Items) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_91f3f3f7c00eaf96, []int{9}
}
func (m *Items) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Items.Unmarshal(m, b)
}
func (m *Items) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Items.Marshal(b, m, deterministic)
}
func (dst *Items) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Items.Merge(dst, src)
}
func (m *Items) XXX_Size() int {
	return xxx_messageInfo_Items.Size(m)
}
func (m *Items) XXX_DiscardUnknown() {
	xxx_messageInfo_Items.DiscardUnknown(m)
}

var xxx_messageInfo_Items proto.InternalMessageInfo

func (m *Items) GetPreTerminals() []*TreeItem {
	if m != nil {
		return m.PreTerminals
	}
	return nil
}

func (m *Items) GetTerminals() []string {
	if m != nil {
		return m.Terminals
	}
	return nil
}

func (m *Items) GetTerminalsCount() uint64 {
	if m != nil {
		return m.TerminalsCount
	}
	return 0
}

type TreeItem struct {
	Index                int32       `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Transition           int32       `protobuf:"varint,2,opt,name=transition,proto3" json:"transition,omitempty"`
	Childrens            []*TreeItem `protobuf:"bytes,3,rep,name=childrens,proto3" json:"childrens,omitempty"`
	Id                   bool        `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TreeItem) Reset()         { *m = TreeItem{} }
func (m *TreeItem) String() string { return proto.CompactTextString(m) }
func (*TreeItem) ProtoMessage()    {}
func (*TreeItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_proto_91f3f3f7c00eaf96, []int{10}
}
func (m *TreeItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreeItem.Unmarshal(m, b)
}
func (m *TreeItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreeItem.Marshal(b, m, deterministic)
}
func (dst *TreeItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreeItem.Merge(dst, src)
}
func (m *TreeItem) XXX_Size() int {
	return xxx_messageInfo_TreeItem.Size(m)
}
func (m *TreeItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TreeItem.DiscardUnknown(m)
}

var xxx_messageInfo_TreeItem proto.InternalMessageInfo

func (m *TreeItem) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *TreeItem) GetTransition() int32 {
	if m != nil {
		return m.Transition
	}
	return 0
}

func (m *TreeItem) GetChildrens() []*TreeItem {
	if m != nil {
		return m.Childrens
	}
	return nil
}

func (m *TreeItem) GetId() bool {
	if m != nil {
		return m.Id
	}
	return false
}

func init() {
	proto.RegisterType((*Empty)(nil), "proto.Empty")
	proto.RegisterType((*NextRequest)(nil), "proto.NextRequest")
	proto.RegisterType((*ConnectResponse)(nil), "proto.ConnectResponse")
	proto.RegisterType((*ResultResponse)(nil), "proto.ResultResponse")
	proto.RegisterType((*CrackingResponse)(nil), "proto.CrackingResponse")
	proto.RegisterMapType((map[string]string)(nil), "proto.CrackingResponse.HashesEntry")
	proto.RegisterType((*Grammar)(nil), "proto.Grammar")
	proto.RegisterMapType((map[string]*IntMap)(nil), "proto.Grammar.MappingEntry")
	proto.RegisterType((*IntMap)(nil), "proto.IntMap")
	proto.RegisterMapType((map[string]int32)(nil), "proto.IntMap.ValueEntry")
	proto.RegisterType((*Replacement)(nil), "proto.Replacement")
	proto.RegisterType((*Section)(nil), "proto.Section")
	proto.RegisterType((*Items)(nil), "proto.Items")
	proto.RegisterType((*TreeItem)(nil), "proto.TreeItem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PCFGClient is the client API for PCFG service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PCFGClient interface {
	Connect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConnectResponse, error)
	Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetNextItems(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*Items, error)
	SendResult(ctx context.Context, in *CrackingResponse, opts ...grpc.CallOption) (*ResultResponse, error)
}

type pCFGClient struct {
	cc *grpc.ClientConn
}

func NewPCFGClient(cc *grpc.ClientConn) PCFGClient {
	return &pCFGClient{cc}
}

func (c *pCFGClient) Connect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/proto.PCFG/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCFGClient) Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.PCFG/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCFGClient) GetNextItems(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*Items, error) {
	out := new(Items)
	err := c.cc.Invoke(ctx, "/proto.PCFG/GetNextItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pCFGClient) SendResult(ctx context.Context, in *CrackingResponse, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/proto.PCFG/SendResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PCFGServer is the server API for PCFG service.
type PCFGServer interface {
	Connect(context.Context, *Empty) (*ConnectResponse, error)
	Disconnect(context.Context, *Empty) (*Empty, error)
	GetNextItems(context.Context, *NextRequest) (*Items, error)
	SendResult(context.Context, *CrackingResponse) (*ResultResponse, error)
}

func RegisterPCFGServer(s *grpc.Server, srv PCFGServer) {
	s.RegisterService(&_PCFG_serviceDesc, srv)
}

func _PCFG_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFGServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PCFG/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFGServer).Connect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCFG_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFGServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PCFG/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFGServer).Disconnect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCFG_GetNextItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFGServer).GetNextItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PCFG/GetNextItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFGServer).GetNextItems(ctx, req.(*NextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PCFG_SendResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrackingResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PCFGServer).SendResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PCFG/SendResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PCFGServer).SendResult(ctx, req.(*CrackingResponse))
	}
	return interceptor(ctx, in, info, handler)
}

var _PCFG_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PCFG",
	HandlerType: (*PCFGServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _PCFG_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _PCFG_Disconnect_Handler,
		},
		{
			MethodName: "GetNextItems",
			Handler:    _PCFG_GetNextItems_Handler,
		},
		{
			MethodName: "SendResult",
			Handler:    _PCFG_SendResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_proto_91f3f3f7c00eaf96) }

var fileDescriptor_proto_91f3f3f7c00eaf96 = []byte{
	// 677 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x54, 0x5b, 0x6f, 0xd3, 0x30,
	0x14, 0x26, 0x6b, 0xd3, 0xcb, 0x49, 0xe9, 0x26, 0x0b, 0x46, 0x55, 0x10, 0x9a, 0x32, 0x09, 0x4d,
	0x20, 0x2a, 0xd1, 0x09, 0x34, 0x2e, 0x6f, 0x65, 0x1b, 0x93, 0x18, 0x42, 0xde, 0xc4, 0x7b, 0xd6,
	0x9a, 0xcd, 0x5a, 0xe2, 0x04, 0xdb, 0x45, 0xeb, 0x13, 0x12, 0x8f, 0xbc, 0xf3, 0xd3, 0x78, 0xe0,
	0xdf, 0xe0, 0x5b, 0x12, 0x67, 0x0c, 0xf1, 0xd2, 0xfa, 0x7c, 0xfe, 0xce, 0xed, 0x3b, 0xf1, 0x81,
	0xa8, 0xe0, 0xb9, 0xcc, 0x27, 0xe6, 0x17, 0x85, 0xe6, 0x2f, 0xee, 0x42, 0xb8, 0x9f, 0x15, 0x72,
	0x15, 0x3f, 0x81, 0xe8, 0x03, 0xb9, 0x92, 0x98, 0x7c, 0x59, 0x12, 0x21, 0xd1, 0x03, 0xe8, 0x4b,
	0xc2, 0x33, 0xca, 0x92, 0x54, 0x8c, 0x82, 0xad, 0x60, 0xa7, 0x8d, 0x6b, 0x20, 0x5e, 0xc1, 0xfa,
	0x2c, 0x67, 0x8c, 0xcc, 0x15, 0x5f, 0x14, 0x39, 0x13, 0x04, 0xed, 0x40, 0xf7, 0x9c, 0x27, 0x59,
	0x96, 0x70, 0x43, 0x8f, 0xa6, 0x43, 0x9b, 0x68, 0x72, 0x68, 0x51, 0x5c, 0x5e, 0xa3, 0x31, 0xf4,
	0x2e, 0x12, 0x71, 0xf1, 0x9e, 0x0a, 0x39, 0x5a, 0xdb, 0x6a, 0xed, 0xf4, 0x71, 0x65, 0xa3, 0x2d,
	0x88, 0xf4, 0x79, 0x9e, 0xc8, 0xe3, 0x7c, 0x41, 0x46, 0x2d, 0x15, 0xa9, 0x8f, 0x7d, 0x28, 0x8e,
	0x61, 0xa8, 0x72, 0x2e, 0xd3, 0x3a, 0xf3, 0x06, 0xb4, 0x08, 0x5b, 0x98, 0xac, 0x3d, 0xac, 0x8f,
	0xf1, 0x8f, 0x00, 0x36, 0x66, 0x3c, 0x99, 0x5f, 0x52, 0x76, 0x5e, 0xd1, 0x5e, 0x43, 0x47, 0xc7,
	0x21, 0xba, 0x9d, 0x96, 0xaa, 0x6f, 0xdb, 0xd5, 0x77, 0x9d, 0x38, 0x79, 0x67, 0x58, 0xfb, 0x4c,
	0xf2, 0x15, 0x76, 0x2e, 0xe3, 0x97, 0x10, 0x79, 0xb0, 0x4e, 0x79, 0x49, 0x56, 0x26, 0x65, 0x1f,
	0xeb, 0x23, 0xba, 0x03, 0xe1, 0xd7, 0x24, 0x5d, 0x12, 0xd5, 0x91, 0xc6, 0xac, 0xf1, 0x6a, 0x6d,
	0x2f, 0x88, 0x7f, 0x07, 0xd0, 0x75, 0x1a, 0xe8, 0xf6, 0xf8, 0x32, 0x25, 0xe2, 0x20, 0x4f, 0x17,
	0x84, 0x3b, 0x7f, 0x1f, 0x42, 0x8f, 0xa1, 0x27, 0x94, 0xac, 0x54, 0x55, 0x62, 0xc4, 0xa9, 0x75,
	0x3c, 0xb1, 0x30, 0xae, 0xee, 0xd1, 0x73, 0xe8, 0x66, 0x49, 0x51, 0xa8, 0xda, 0x95, 0x50, 0x9a,
	0x7a, 0xbf, 0x29, 0xf9, 0xe4, 0xd8, 0xde, 0xda, 0x56, 0x4a, 0xee, 0xf8, 0x08, 0x06, 0xfe, 0xc5,
	0x0d, 0xcd, 0x6c, 0xfb, 0xcd, 0x44, 0xd3, 0xdb, 0x2e, 0xec, 0x11, 0x93, 0xca, 0xd1, 0xef, 0x8d,
	0x43, 0xc7, 0x82, 0x68, 0x52, 0xba, 0x58, 0x71, 0x47, 0x0d, 0x97, 0xc9, 0x27, 0x7d, 0x65, 0xcb,
	0xb0, 0xb4, 0xf1, 0x1e, 0x40, 0x0d, 0xfe, 0x4f, 0xcf, 0xd0, 0xcf, 0xf9, 0x33, 0x80, 0x08, 0x93,
	0x22, 0x4d, 0xe6, 0x24, 0x23, 0xcc, 0x7c, 0x32, 0x2a, 0xd7, 0x59, 0x72, 0x46, 0x53, 0x2a, 0x6d,
	0x8c, 0x00, 0xfb, 0x10, 0x7a, 0x08, 0x40, 0xc5, 0xa9, 0xfb, 0x78, 0x4d, 0xc0, 0x1e, 0xf6, 0x10,
	0xb4, 0x09, 0x1d, 0x13, 0x5e, 0x18, 0x19, 0xfb, 0xd8, 0x59, 0xfa, 0x43, 0xfd, 0xbc, 0x64, 0x46,
	0xec, 0x51, 0xdb, 0x94, 0x56, 0xd9, 0xba, 0xe2, 0x22, 0x17, 0xa3, 0x50, 0x39, 0x84, 0x58, 0x1f,
	0x63, 0x0a, 0x5d, 0x37, 0x22, 0x84, 0xa0, 0x2d, 0x57, 0x05, 0x71, 0xfd, 0x98, 0xb3, 0xc6, 0x58,
	0x92, 0x95, 0xdf, 0x87, 0x39, 0xa3, 0x17, 0x30, 0xe0, 0x75, 0x27, 0xc2, 0x4d, 0x11, 0x39, 0xed,
	0xbc, 0x26, 0x71, 0x83, 0x17, 0x7f, 0x0f, 0x20, 0x3c, 0x92, 0x24, 0x13, 0x68, 0x17, 0x06, 0x05,
	0x27, 0xa7, 0xde, 0x4b, 0xd5, 0x11, 0xd6, 0x5d, 0x84, 0x53, 0x4e, 0x88, 0xe6, 0xe1, 0x06, 0xa9,
	0xf9, 0xb6, 0xed, 0x0b, 0xac, 0x01, 0xf4, 0x08, 0x86, 0x95, 0x31, 0xcb, 0x97, 0x4c, 0x9a, 0x57,
	0xd8, 0xc6, 0xd7, 0xd0, 0xf8, 0x1b, 0xf4, 0xca, 0xf8, 0x7a, 0x5a, 0x94, 0x2d, 0xc8, 0x95, 0xe9,
	0x58, 0x4d, 0xcb, 0x18, 0x5a, 0x77, 0xc9, 0x13, 0x26, 0xa8, 0x51, 0xd0, 0x0e, 0xd2, 0x43, 0xd0,
	0x53, 0xe8, 0xcf, 0x2f, 0x68, 0xba, 0xe0, 0x84, 0x95, 0xbd, 0xff, 0x55, 0x79, 0xcd, 0x40, 0x43,
	0x58, 0xa3, 0x0b, 0x33, 0x88, 0x1e, 0x56, 0xa7, 0xe9, 0xaf, 0x00, 0xda, 0x1f, 0x67, 0x07, 0x87,
	0xe8, 0x19, 0x74, 0xdd, 0x36, 0x42, 0x03, 0xe7, 0x6f, 0x76, 0xda, 0x78, 0xb3, 0x7c, 0xe2, 0xcd,
	0x5d, 0x15, 0xdf, 0x52, 0xdb, 0x0a, 0xde, 0x52, 0x31, 0xbf, 0xd1, 0xab, 0x61, 0xa1, 0x29, 0x0c,
	0x0e, 0x89, 0xd4, 0xab, 0xd1, 0x2a, 0x5e, 0x4e, 0xc7, 0x5b, 0x96, 0x95, 0x87, 0x61, 0xa8, 0xe8,
	0x6f, 0x00, 0x4e, 0xd4, 0x1e, 0xb2, 0x7b, 0x0a, 0xdd, 0xfb, 0xc7, 0xa2, 0x19, 0xdf, 0xad, 0x06,
	0xed, 0xef, 0xb3, 0xb3, 0x8e, 0x41, 0x77, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x52, 0xf9,
	0x23, 0xaf, 0x05, 0x00, 0x00,
}
