#! /bin/sh
### BEGIN INIT INFO
# Provides:          fitcrack
# Required-Start:    $local_fs $network mysql
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Fitcrack services
### END INIT INFO

DESC="Fitcrack services"
NAME=fitcrack
DAEMON=/home/boincadm/projects/fitcrack/bin/start
START_OPTION=--start
STOP_OPTION=--stop
STATUS_OPTION=--status
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
  start)
    sudo -u boincadm $DAEMON $START_OPTION
    ;;

  stop)
    sudo -u boincadm $DAEMON $STOP_OPTION
    ;;

  status)
    sudo -u boincadm $DAEMON $STATUS_OPTION
    ;;

  restart)
    sudo -u boincadm $DAEMON $STOP_OPTION
    sudo -u boincadm $DAEMON $START_OPTION
    ;;

  *)
    echo "Usage: $SCRIPTNAME {start|stop|status|restart}" >&2
    exit 3
    ;;
esac
