#!/bin/bash

# Set variable values to default ones
# This file is part of Fitcrack installer
# Author: David Bolvansky

COMPILER_THREADS=${COMPILER_THREADS:-8}
BOINC_USER=${BOINC_USER:-boincadm}
BOINC_GROUP=${BOINC_GROUP:-$BOINC_USER}
BOINC_HOME=${BOINC_HOME:-/home/$BOINC_USER}
BOINC_PROJECT=${BOINC_PROJECT:-fitcrack}
BOINC_PROJECT_DIR="$BOINC_HOME/projects/$BOINC_PROJECT"
PROJECT_HTTPD_CONF="$BOINC_PROJECT_DIR/$BOINC_PROJECT.httpd.conf"
BOINC_URL=${BOINC_URL:-http://127.0.0.1}
BOINC_URL=${BOINC_URL%/}
APACHE_USER=${APACHE_USER:-$DEFAULT_APACHE_USER}
APACHE_GROUP=${APACHE_GROUP:-$APACHE_USER}
APACHE_CONFIG_DIR=${APACHE_CONFIG_DIR:-$DEFAULT_APACHE_CONFIG_DIR}
APACHE_CONFIG_FILE=${APACHE_CONFIG_FILE:-$DEFAULT_APACHE_CONFIG_FILE}
APACHE_SERVICE=${APACHE_SERVICE:-$DEFAULT_APACHE_SERVICE}
APACHE_DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT:-$DEFAULT_APACHE_DOCUMENT_ROOT}
DB_HOST=${DB_HOST:-localhost}
DB_NAME=${DB_NAME:-fitcrack}
DB_USER=${DB_USER:-fitcrack}
DB_PW=${DB_PW:-mypassword}